using UnityEngine;

namespace WFC
{
    public class WaveFunctionCollapseController : MonoBehaviour
    {
        [Header("References")]
        [SerializeField] private WaveFunctionCollapse m_WaveFuncionCollapse;
        [SerializeField] private InputManager m_InputManager;
        
        [Space(10)]
        
        [Header("Grid Settings")]
        [SerializeField] private int m_GridWidth;
        [SerializeField] private int m_GridHeight;
        [SerializeField] private int m_NumberOfManualStepps = 1;
        [SerializeField] private int m_AutoGenerateDelayMS = 5;
        [SerializeField] private bool m_ManualCollapse = false;

        private Camera m_MainCamera;

        private void Awake()
        {
            m_MainCamera = Camera.main;
        }

        private async void Start()
        {
            m_WaveFuncionCollapse.GenerateGrid(m_GridWidth, m_GridHeight, out Vector3 gridCenter);
            m_MainCamera.transform.position = gridCenter;
            
            if (!m_ManualCollapse)
            {
                await m_WaveFuncionCollapse.GenerateAuto(m_AutoGenerateDelayMS, () => Debug.Log("callback working"));
            }
        }

        private void Update()
        {
            if (!m_ManualCollapse) return;

            if (m_InputManager.ManualGenerate)
            {
                m_WaveFuncionCollapse.GenerateStep(m_NumberOfManualStepps);
            }
        }
    }
}

